//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossLang.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossLang.ApplicationCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng liện hệ bộ phận hỗ trợ CrossLang để được tư vấn.
        /// </summary>
        internal static string CrossLang_ResponseMessage_Default {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;{1}&gt; đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        internal static string CrossLang_ResponseMessage_Duplicated {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng email..
        /// </summary>
        internal static string CrossLang_ResponseMessage_InvalidEmail {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng số điện thoại..
        /// </summary>
        internal static string CrossLang_ResponseMessage_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống.
        /// </summary>
        internal static string CrossLang_ResponseMessage_IsNull {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} ký tự.
        /// </summary>
        internal static string CrossLang_ResponseMessage_MaxLengthExceeded {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là kiểu UUID.
        /// </summary>
        internal static string CrossLang_ResponseMessage_NotUUID {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.NotUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi với {0} &lt;{1}&gt; không tồn tại.
        /// </summary>
        internal static string CrossLang_ResponseMessage_RecordIdNotExists {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.RecordIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác động bản ghi trong CSDL thất bại.
        /// </summary>
        internal static string CrossLang_ResponseMessage_RowAffectingUnexpectedFailure {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.RowAffectingUnexpectedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không tồn tại.
        /// </summary>
        internal static string CrossLang_ResponseMessage_TokenNotFound {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        internal static string CrossLang_ResponseMessage_UserNotFound {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác.
        /// </summary>
        internal static string CrossLang_ResponseMessage_WrongPassword {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc không được nhỏ hơn thời gian bắt đầu.
        /// </summary>
        internal static string CrossLang_ResponseMessage_WrongTimeOrder {
            get {
                return ResourceManager.GetString("CrossLang.ResponseMessage.WrongTimeOrder", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string CrossLang_ResponseMessage_NotValid
        {
            get
            {
                return ResourceManager.GetString("CrossLang.ResponseMessage.NotValid", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string CrossLang_ResponseMessage_Duplicate_Username
        {
            get
            {
                return ResourceManager.GetString("CrossLang_ResponseMessage_Duplicate_Username", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string CrossLang_ResponseMessage_Duplicate_Email
        {
            get
            {
                return ResourceManager.GetString("CrossLang_ResponseMessage_Duplicate_Email", resourceCulture);
            }
        }

        /// <summary>
        /// </summary>
        internal static string CrossLang_ResponseMessage_NoPermission
        {
            get
            {
                return ResourceManager.GetString("CrossLang.ResponseMessage.NoPermission", resourceCulture);
            }
        }
    }
}
